version: '3.8'
services:
  app:
    build:
      context: ./docker/node
      args:
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - "${APP_PORT}:3000"
    restart: on-failure
    depends_on: [ database ]
  database:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}