version: '3.8'
services:
  app:
    build:
      context: ./docker/node
    volumes:
      - .:/usr/local/app
    restart: on-failure
    depends_on: [ database ]
  database:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
  server:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/usr/local/app
    depends_on:
      - app